### PR TITLE
Code cleanup, reduce disk I/O

### PR DESCRIPTION
**Pull request by xxFlare**

### CODE REVIEW

**Comment by Gamecrafter** [comment]
@xxFlare Can you please stop opening and closing pull requests? It gets annoying.

**Comment by xxFlare** [comment]
@Gamecrafter Some of these are fixes, in our slack team we usually discuss ones that should be added or not.

**Comment by Gamecrafter** [comment]
@xxFlare Well then you should discuss it *before* creating the pull request?

**Comment by PEMapModder** [comment]
@gamecrafter this repo is like this. Unwatch if you find it annoying. Just that they moved the discussion you expected to be done on GitHub to slack and you can't see it.

**Pull request closed without merging**
