### PR TITLE
New Item Functions

### PR DESCRIPTION
**Pull request by junkdude**
This PR adds some new item functions.

### CODE REVIEW

**Comment by SuperMaXAleX** [comment]
You did totally all wrong about lores.

**Comment by junkdude** [comment]
@SuperMaXAleX  its literally from pmmp itself

**Comment by SuperMaXAleX** [comment]
Copy-paste isn't accepted, first.
Second, lores need a packet and others things.

**Comment by BI0MER** [comment]
Leave this repository, please
We do not need such help

**Pull request closed without merging**
