### PR TITLE
protocol 401

### PR DESCRIPTION
**Pull request by EmeraldTorch**
1.16.0.53 has been released today and its protocol version is 401

### CODE REVIEW

**Comment by Kenilworth** [comment]
ahaha, have you checked at least your pull request?

**Comment by EmeraldTorch** [comment]
https://minecraft.gamepedia.com/Bedrock_Edition_beta_1.16.0.53
It's protocol 401

**Comment by EmeraldTorch** [comment]
> ahaha, have you checked at least your pull request?

https://minecraft.gamepedia.com/Bedrock_Edition_beta_1.16.0.53
It's protocol 401

**Comment by Kenilworth** [comment]
@EmeraldTorch Just haha, better close the pull request please

**Pull request closed without merging**
