### PR TITLE
New Update All Doors have been added and work

### PR DESCRIPTION
**Pull request by DavidJBrockway**
Door that have been added and tested are:
Oak Door	
Spruce Door	
Birch Door	
Jungle Door	
Acacia Door	
Dark Oak Door	

Bugs are on block break half the door is broken first then it is destored i am working on the fix

### CODE REVIEW

**Comment by DavidJBrockway** [comment]
Here are images as proff that the Doors work.

**Comment by DavidJBrockway** [comment]
img_0634
img_0635
img_0636

**Comment by DavidJBrockway** [comment]
Thanks when will it be added to master code?

**Comment by DavidBrockway** [comment]
Reopen this

**Comment by SuperMaXAleX** [comment]
Why?

**Pull request closed without merging**
