### PR TITLE
Fixed FloatingTextParticle alignment

### PR DESCRIPTION
**Pull request by GiantQuartz**
I still don't understand what is the point of that linefeed, it is just breaking FloatingTextParticle alignment.

### CODE REVIEW

**Comment by TheRoyalBlock** [comment]
looks good!

**Comment by vchibikov** [comment]
Not good, new line symbol separated the title and main text. Now everything is indistinguishable.

**Comment by GiantQuartz** [comment]
Oh, I just realized that you're right. Thanks.

**Comment by TheRoyalBlock** [comment]
Oh, yeah... Forgive my errors, I usually do not work with the softwares themselves

**Comment by GiantQuartz** [comment]
@vchibikov Anyway, what is the point of having the title and the text on different variables? I don't think it makes sense, it just makes floating texts more confusing. 

Changing the order of the arguments on FloatingTextParticle constructor might also be a good idea, if the title goes first, why is the text requested first?

**Pull request closed without merging**
