### PR TITLE
added rain and lightning level into server.properties

### PR DESCRIPTION
**Pull request by vchibikov**

### CODE REVIEW

**Comment by dktapps** [comment]
wat

**Comment by yoraze** [comment]
@dktapps "why not"? :)

**Comment by kroer** [comment]
@dktapps Do you know the way how to change it in the game using packets? And not just enable or disable but set intensity.

**Comment by yoraze** [comment]
@kroer LevelEventPacket.

**Comment by dktapps** [comment]
@kroer Yes. See https://github.com/pmmp/PocketMine-MP/blob/feature/weather/src/pocketmine/level/Level.php#L690-L704. The code is old but it conveys the gist of it.

**Comment by kroer** [comment]
@dktapps Thanks

**Pull request merged**
