### PR TITLE
Mineplex uses Steadfast2 too.

### PR DESCRIPTION
**Pull request by NycuRO**

### CODE REVIEW

**Comment by dishrex** [comment]
Mineplex does not use Steadfast2...

**Comment by NycuRO** [comment]
@dishrex Yes, them use, lol.

**Comment by HerryYT** [comment]
they uses Mi Net or Nukkit, but i'm sure no stadfast or pocketmine

**Comment by kaliiks** [comment]
@HerryYT You are only the one who don't know, FTL support for MiNET was dropped 8 months ago or more

**Pull request closed without merging**
