### PR TITLE
Production

### PR DESCRIPTION
**Pull request by MFDGaming**
Hydreon can you stop using pocketmine as the base and use genisys pro?
Genisys pro is better for stability and world generation.
Can you please do me this favor?

### CODE REVIEW

**Comment by dktapps** [comment]
You might want to go back to the brain factory and get a refund.

**Comment by dktapps** [comment]
@GiantQuartz Indeed, but I decided to express my thoughts anyway. Your comment is also unnecessary if you want to start this flame war.

**Comment by MFDGaming** [comment]
I sed this before because of the gravity wen it is on android php 7.0.3
Ps Genisys pro works fine on android php 7.0.3
That’s all
Ps dktapps stop being bad

**Comment by MFDGaming** [comment]
Sorry for my English

**Comment by alexfox18** [comment]
@dktapps there are a lot of bugs in Steadfast2, they are not even implemented enchantments, the talk about GenisysPro is just as normal.

**Comment by dktapps** [comment]
Missing features != less stability. Sure Steadfast has bugs, but LBSG has been running it in production for many years now, and the whole point of this fork was to be a stripped back high performance build of PM fit for production use. These guys know what they are doing, unlike the noobs who created GenisysPro.

**Comment by alexfox18** [comment]
@dktapps Steadfast2 has a lot of bugs, not to mention adding other things. Even LBSG has already begun to somehow fix the core, add something of its own, and there is not even half of it. If you put this core, then as if you were back in 2014.

**Comment by MFDGaming** [comment]
Can anyone at least fix android php 7.0.3 gravity bug

**Comment by MFDGaming** [comment]
I want do make a community server with multi protocol on an armv7l android 6 php 7.0.3 device

**Comment by MFDGaming** [comment]
Can anyone fix this bug as soon as possible?

**Comment by HerryYT** [comment]
@alexfox18 lbsg by hidreon created this software.. so is they didn't had to edit nothing because is already written by them..

**Comment by MFDGaming** [comment]
But can you fix it and upload it in an other repo

**Comment by MFDGaming** [comment]
Pls answer

**Comment by MFDGaming** [comment]
@HerryYT can you fix this bug

**Comment by HerryYT** [comment]
@kroer There are a lot of bugs due to PHP 7.0.x x32 Bit, that's why PocketMineMP (@dktapps) dropped x32 support, steadfast should do sane because in Android, Linux there will be infinite bugs.

**Comment by kroer** [comment]
@HerryYT give me a list of bugs, please. If they real we will trying to fix them

**Comment by MFDGaming** [comment]
Gravity bug 
i float over my building 
I cant jump

**Comment by MFDGaming** [comment]
@kroer ^
              |

**Comment by MFDGaming** [comment]
@kroer 
Gravity bug
i float over my building
I cant jump

**Comment by kroer** [comment]
@MFDGaming What is your client version and protocol?

**Comment by Mespeczek** [comment]
I found one more bug. I can't format my chat using any plugins and without plugins i can't use color text in chat
( I can send screenshot

**Comment by MFDGaming** [comment]
@kroer 280, 281, 282

**Comment by MFDGaming** [comment]
@kroer mcpe 1.6

**Comment by Mespeczek** [comment]
Here are screenshots

**Comment by kroer** [comment]
@Mespeczek it is not bug. It was done on purpose (https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/Player.php#L2178).

@MFDGaming thanks, we check this

@alexfox18 thanks but most of your list items not a bugs but not implemented features. But last two are interested. What wrong with sendTitle? What version and protocol of client i should use to reproduce bug with blocks?

**Comment by alexfox18** [comment]
@kroer Well, still implement it. sendTitle, you need to do it on a new API, just send sendTitle ("message", "message2"); and in Steadfast2 sendTitle ("message", "message2" $ time = 50); You removed version 1.0.5, now you can add cement, concrete, etc.

**Comment by alexfox18** [comment]
@kroer when to wait for fixes / additions from my list?

**Comment by Mespeczek** [comment]
@kroer How can I make the colors work? I prefer not to rummage in the code myself.

**Comment by kroer** [comment]
@Mespeczek just remove this line https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/Player.php#L2178

**Comment by MFDGaming** [comment]
@kroer can you make a version of steadfast for php 5

**Comment by HerryYT** [comment]
@kroer i have a problem, how can i contact you?

**Comment by MFDGaming** [comment]
@kroer I have a problem, how can i contact you?

**Comment by Mespeczek** [comment]
@kroer Can you repair RCON?

**Comment by alexfox18** [comment]
@kroer Previously worked, with the update ceased, how to fix?

src/pocketmine/level/generator/normal/Normal.php(315): pocketmine\level\generator\normal\populator\Cave->populate(Object(pocketmine\level\SimpleChunkManager), 618, 207, Object(pocketmine\utils\Random))
src/pocketmine/level/generator/PopulationTask.php(120): pocketmine\level\generator\normal\Normal->populateChunk(618, 207)
src/pocketmine/scheduler/AsyncTask.php(43): pocketmine\level\generator\PopulationTask->onRun()                                                                                       #3 [internal function]: pocketmine\scheduler\AsyncTask->run()
src/pocketmine/level/generator/normal/populator/Cave.php on line 45
Could not execute asynchronous task pocketmine\level\generator\PopulationTask

**Comment by Mespeczek** [comment]
@kroer

Can you add ListTag.php to `src/pocketmine/nbt/`?
It's needed for pmmp plugins what create NPC/Slapper on server.

Or...

Is there another way to create an NPC on the server?

Please Answer :smile:

**Comment by MFDGaming** [comment]
@Mespeczek get this version https://drive.google.com/file/d/1Kw6WRLwp5RqcjrvqfWpJYu7z43e2ghqZ/view?usp=drivesdk I hve fixed the nbt and other tiny bugs for plugins

**Comment by Saxavlax001** [comment]
Guys how can I make purechat work with steadfast2?I'm thinking to make a multiversion server,but I have problem with ranks.

**Comment by MFDGaming** [comment]
@Saxavlax001 what error did you get?
Did you get an uncompatible api version error

**Comment by MFDGaming** [comment]
@Saxavlax001 try this version of purechat https://drive.google.com/file/d/1eiW9S4eTZtt1U9EN8TYV3I1HDTZruiP7/view?usp=drivesdk

**Comment by MFDGaming** [comment]
Thia version will work

**Comment by MFDGaming** [comment]
https://drive.google.com/file/d/1eiW9S4eTZtt1U9EN8TYV3I1HDTZruiP7/view?usp=drivesdk

**Comment by Saxavlax001** [comment]
@MFDGaming no I don't have any error like incompatible api version,but I have another problem:Ranks don't work,I mean any formats of PureChat plugin.And I have already installed the PurePerms plugin.

**Comment by Saxavlax001** [comment]
No errors just any format of purechat don't work.

**Comment by MFDGaming** [comment]
Oh

**Comment by MFDGaming** [comment]
I think I know how to fix that

**Comment by Saxavlax001** [comment]
And I have edited the latest purechat and pureperms to work with steadfast2.

**Comment by MFDGaming** [comment]
Give me pure perms so that I can try to fix it

**Comment by Saxavlax001** [comment]
[PurePermsandchat.zip](https://github.com/Hydreon/Steadfast2/files/2783453/PurePermsandchat.zip)

**Comment by Saxavlax001** [comment]
PurePerms and PureChat

**Comment by Saxavlax001** [comment]
Ok its spam,but I can't find any steadfast2 dev to get help and @MFDGaming if you fixed it send me somewhere or here the fixed plugin if you can pls.

**Comment by MFDGaming** [comment]
the problem is steadfast not the plugin

**Comment by MFDGaming** [comment]
If you want us to contine chating in here email me alexandros.argentakis@gmail.com

**Comment by Mespeczek** [comment]
@MFDGaming can you help me? RCON didn't work.

**Pull request closed without merging**
