### PR TITLE
Spruce up

### PR DESCRIPTION
**Pull request by Enes5519**
**TODO:**
- [x] New Packet Handler (from Turanic)
- [x] Cleanups
  - [x] Arrow & Item Pickup
  - [x] Entity->spawnTo
- [ ] Optimize
- [ ] ***moree...***

### CODE REVIEW

**Comment by dktapps** [comment]
lol

**Comment by HerryYT** [comment]
what :D

**Comment by XFIREGANER** [comment]
Enes5519, Your Software (Steadfast)
if I Died, The server is closed? 
Fix your software

**Comment by Enes5519** [comment]
@XFIREGANER I don't find world for Steadfast.

**Comment by dktapps** [comment]
do you seriously expect anyone to even consider merging this... ?

**Comment by Enes5519** [comment]
No 👎. I'm just bored. @dktapps Please pardon me on pmmp.

**Comment by HerryYT** [comment]
Add fix DataPacketReciveEvent :'D

**Comment by Enes5519** [comment]
@HerryYT Fix with new packet handler :D https://github.com/Enes5519/Steadfast2/blob/master/src/pocketmine/Player.php#L2583

**Comment by alexfox18** [comment]
@dktapps Hello, I don't know how you can be contacted. I wanted to ask you, can you give contacts to the developers of the kernel Steadfast2? Very much needed, please

**Pull request closed without merging**
