### PR TITLE
Update Item.php

### PR DESCRIPTION
**Pull request by DavidBrockway**
Updated Creative Item Layout, Added most of the missing blocks to the //ToDo tags.

### CODE REVIEW

**Comment by DavidBrockway** [comment]
Added some missing blocks to todo list some items still missing from todo list from Tools and the other tab next to tools.

**Comment by AppleDevelops** [comment]
Item ID 116 isn’t proper
ENCHANTING_ isn’t valid

**Comment by DavidBrockway** [comment]
Fixed

**Comment by AppleDevelops** [comment]
The next issue I have isn’t an actual issue but some people prefer TODO: instead of ToDo

**Comment by DavidBrockway** [comment]
Not an issue, its just you begging picky.

**Comment by SuperMaXAleX** [comment]
@DavidBrockway Why have you deleted `ENCHANT_TABLE` ? Anvil block ? Ender chest block ? End rod block ? Sign block ? Chorus plant block ? End Bricks block ? Purpur block ?

**Comment by DavidBrockway** [comment]
I haven't I just moved the items in the lost in the correct inventory order.

**Comment by DavidBrockway** [comment]
I haven't I just moved the items in the lost in the correct inventory order.

**Pull request closed without merging**
