### PR TITLE
Fixed split packets being sent in too-large parts

### PR DESCRIPTION
**Pull request by dktapps**
see description of https://github.com/pmmp/RakLib/commit/226772184b6cb3c014477feb41e55ec22850f2dd for details

### CODE REVIEW

**Comment by dktapps** [comment]
Note that this does not resolve all MTU size related issues in RakLib, it's still screwed up. However this change fixes one specific major issue.

**Comment by vchibikov** [comment]
Thanks, but we already have lower mtuSize than PocketMine https://github.com/Hydreon/Steadfast2/blob/master/src/raklib/server/Session.php#L528

**Comment by dktapps** [comment]
@vchibikov This isn't about the actual MTU size itself, it's about the padding. You can see it yourself in packets sent by the client. Lowering the MTU size does nothing if you're still sending packets larger than the client is expecting to receive.

**Comment by dktapps** [comment]
Some numbers: 
- Steadfast will still send packets up to 1398 bytes in size
- but the client will expect to receive a maximum of 1372 bytes with an MTU size of 1432
- the maximum size of a split packet you will receive from a client with MTU 1432 is 1372 bytes.

**Comment by dktapps** [comment]
Thanks!

**Pull request merged**
