### PR TITLE
Update Human.php

### PR DESCRIPTION
**Pull request by Creeperface01**

### CODE REVIEW

**Comment by PEMapModder** [comment]
explanatino?

**Comment by Creeperface01** [comment]
Player->getNameTag() always returns TESTIFICATE

**Comment by PEMapModder** [comment]
Have you tested what would happen if you do this?

**Comment by PEMapModder** [comment]
Then you should add a setter that modifies $this->nameTag when player has the name tag defined (upon receiving LOGIN_PACKET), not to delete the nametag. If you delete it, Player->getNameTag() would most likely result in an undefined property error or null.

**Comment by Creeperface01** [comment]
But entity class have $nametag and method getNameTag()

**Comment by Creeperface01** [comment]
Or why steadfast added this variable to human class?

**Comment by PEMapModder** [comment]
Oh, never mind, I didn't notice that.

**Pull request closed without merging**
