### PR TITLE
how can i format the chat with plugins?

### PR DESCRIPTION
**Pull request by MFDGaming**
The colors and formats take effect only with the /say command
How can I fix it?

### CODE REVIEW

**Comment by archie426** [comment]
question: why are you making pull requests for support?

**Comment by MFDGaming** [comment]
There is no issues page that's why

**Comment by dktapps** [comment]
did you consider the possibility that there's no issues page BECAUSE they don't want spam like this?

**Comment by MFDGaming** [comment]
Can you at least answer to my question ?

**Pull request closed without merging**
