### PR TITLE
Protocol 431

### PR DESCRIPTION
**Pull request by fikusreload**
### VIDEO PROOF: https://youtu.be/DF8EatFQPLo

_when you right-click, some blocks change to buttons or change their meta. in addition, when logging in from protocol 428, the client has an eternal search for the server, and in the console it is disconnected_

### CODE REVIEW

**Comment by nazthelizard122** [comment]
> ### ISSUE. BUG
> 
> ### VIDEO PROOF: https://youtu.be/DF8EatFQPLo
> 
> 
> 
> 
> 
> _when you right-click, some blocks change to buttons or change their meta. in addition, when logging in from protocol 428, the client has an eternal search for the server, and in the console it is disconnected_

This has happened on my cactus farms, not a big deal you just need to cause a block update and it will revert

**Comment by fikusreload** [comment]
> This has happened on my cactus farms, not a big deal you just need to cause a block update and it will revert

how to do it?

**Comment by nazthelizard122** [comment]
> > This has happened on my cactus farms, not a big deal you just need to cause a block update and it will revert
> 
> how to do it?

you just press the button

**Comment by fikusreload** [comment]
> > > This has happened on my cactus farms, not a big deal you just need to cause a block update and it will revert
> > 
> > 
> > how to do it?
> 
> you just press the button

ahahah. how i can fix it?

**Comment by nazthelizard122** [comment]
> > > > This has happened on my cactus farms, not a big deal you just need to cause a block update and it will revert
> 
> > > 
> 
> > > 
> 
> > > how to do it?
> 
> > 
> 
> > you just press the button
> 
> 
> 
> ahahah. how i can fix it?

I have no clue. maybe create a script that reverses the bug?

**Comment by fikusreload** [comment]
> > > > > This has happened on my cactus farms, not a big deal you just need to cause a block update and it will revert
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > how to do it?
> > 
> > 
> > > 
> > 
> > 
> > > you just press the button
> > 
> > 
> > ahahah. how i can fix it?
> 
> I have no clue. maybe create a script that reverses the bug?

good luck... give me feedback

**Comment by nazthelizard122** [comment]
> > > > > > This has happened on my cactus farms, not a big deal you just need to cause a block update and it will revert
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > how to do it?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > you just press the button
> 
> > > 
> 
> > > 
> 
> > > ahahah. how i can fix it?
> 
> > 
> 
> > I have no clue. maybe create a script that reverses the bug?
> 
> 
> 
> good luck... give me feedback

I'm not a coder/developer

**Pull request closed without merging**
