### PR TITLE
account hacked

### PR DESCRIPTION
**Pull request by TheDiamondYT1**
wrong repo

### CODE REVIEW

**Comment by GiantQuartz** [comment]
Where's the report button?

**Comment by TheDiamondYT1** [comment]
@GiantQuartz Right here:

screenshot_2017-08-14-23-54-54

**Comment by daniktheboss** [comment]
Oh, look a wild idiot appeared

**Comment by dishrex** [comment]
[https://twitter.com/dishrex/status/897264944118476801](https://twitter.com/dishrex/status/897264944118476801)

**Pull request closed without merging**
