### PR TITLE
Adding .phar file by me

### PR DESCRIPTION
**Pull request by piyushbest**
.phar by piyushbest

### CODE REVIEW

**Comment by Zadezter** [comment]
Seriously, @piyushbest? You've only updated their `README.md` file.

**Comment by piyushbest** [comment]
BRO MY FIRST MOBILE GET BREAK I NEED NEW ONE OF 64 BIT SO I WILL MAKEPHAR LATER ON MY NEW MOBILE

**Comment by T14Raptor** [comment]
You need to chill bro.

**Comment by Zadezter** [comment]
OoF!

**Comment by Zadezter** [comment]
I got here after saw message from GMail.

**Comment by dktapps** [comment]
I know DevTools is a little slow, but it sure doesn't take 2 months to build a server phar file.

**Pull request closed without merging**
